#https://github.com/disney/meteor-base/blob/master/example/docker-compose.yml

version: '3'
networks:
  seb-as:
    external: false
    driver: bridge  

services:
  app:
    container_name: seb-as-app
    networks:
      - seb-as
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000

  mongo:
    container_name: seb-as-mongo
    networks:
      - seb-as
    ports:
      - 11017:27017 #permitir acceso desde el PC
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data: